# Basic function options
x-function: &servicetemplates
  labels:
    function: "true"
  networks:
    - pipeline-networks
  init: true
  restart: always

version: '3.8'
services:

#---> Zookeeper server
  zookeeper:
    <<: *servicetemplates
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "2181"]
      interval: 10s
      retries: 3
      start_period: 10s
      timeout: 5s

#---> Kafka Broker server
  kafka:
    <<: *servicetemplates
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "9092"]
      interval: 10s
      retries: 3
      start_period: 10s
      timeout: 5s
    depends_on:
      zookeeper:
        condition: service_started
networks:
  pipeline-networks:
    driver: bridge
